### ISSUE TITLE
Jukebox-activity failed to start

### ISSUE THREAD

**Issue by vipulgupta2048** [sugarlabs/jukebox-activity#21]
I recently downloaded and ran the jukebox activity and it failed to start.

**Comment by rhl-bthr** [comment]
Activity works on Ubuntu 16.04 Sugar 0.112
Please share logs, and your development environment.

**Comment by vipulgupta2048** [comment]
Here are the logs, and I use sucrose running on Xubuntu 16.04

```
/usr/lib/python2.7/dist-packages/sugar3/graphics/icon.py:34: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Rsvg
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 169, in <module>
    main()
  File "/usr/bin/sugar-activity", line 121, in main
    module = __import__(module_name)
  File "/home/vipulgupta2048/Activities/Jukebox.activity/activity.py", line 53, in <module>
    from player import GstPlayer
ImportError: cannot import name GstPlayer
Exited with status 1, pid 5039 data (None, <open file '<fdopen>', mode 'w' at 0x7fc75fe9a390>, 'b01b30f2fa9458fc7ca271d74dad8f7fcafa5af2')
```

**Comment by quozl** [comment]
Line numbers in your traceback do not match the current `bin/sugar-activity`; the call to `main()` should be closer to line 219 than line 169.  You have a much shorter `/usr/bin/sugar-activity`.  What version of Sugar is your /usr/bin/sugar-activity from?

```bash
dpkg-query -W $(dpkg -S /usr/bin/sugar-activity | cut -f1 -d:)
```

You most likely have an old version of https://github.com/sugarlabs/sugar-toolkit-gtk3 installed prior to a fix to the Python path https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/495eed8737afa53e13878929e386c3e604a65818.

You can either cherry-pick the fix to Sugar Toolkit, upgrade your version of Sugar Toolkit, or temporarily avoid the problem in Jukebox by either removing the Python Pillow package (which has a player.py file in the system path), or renaming the `player.py` file and imports.

**Comment by quozl** [comment]
> I tried deleting the Python-Pillow package and following the steps that you mentioned but it didn't work.

In what way did it not work?

Can you import by hand from the Python interpreter?

**Comment by vipulgupta2048** [comment]
- The activity failed to work, I meant. 
- Import what exactly?

**Comment by quozl** [comment]
There's more to _failed to work_?  Some sort of log?  The log you posted 11 days ago shows an import failed.  That's the import you could try by hand from within the Python interpreter.

The import is here; https://github.com/sugarlabs/jukebox-activity/blob/master/activity.py#L55

The class being imported is here; https://github.com/sugarlabs/jukebox-activity/blob/master/player.py#L31

**Comment by quozl** [comment]
I've tested again, and with the current version of Sugar in Ubuntu 18.04, there's no outstanding issue.  If you need support for installing Ubuntu, please ask more people to help.
